version: '3'

services:
  db:
    container_name: mean-db
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
    #Puerto de la PC : Puerto del contenedor
      - 27017:27017
    restart: always